services:
  nextjs:
    container_name: nextjs
    build:
      context: .
      dockerfile: ./docker/nextjs/Dockerfile
    ports:
      - 3001:3000
    volumes:
      - ./app:/app
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    restart: always
